name: 'ng2_dart_notes'
version: 0.0.1
description: >
  A Notes application made with Angular 2
author: Andres Araujo <a.araujo.azua@gmail.com>
homepage: http://andresaraujo.github.io/ng2_dart_notes/
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular2: "^2.0.0-alpha.44"
  browser: any
transformers:
  - angular2:
      entry_points: web/main.dart